"""empty message

Revision ID: c323b0926db5
Revises: a050f98f398e
Create Date: 2019-12-16 01:43:48.992000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c323b0926db5'
down_revision = 'a050f98f398e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'favorite')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=120), nullable=True))
    op.add_column('history', sa.Column('favorite', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
